apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: yusung1017/spring-server:1.0  # 업데이트 시 태그 변경 필요
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
